---
shift:
  damp: 0.1
stats:
  period: 5
wavefunction:
  nw_init: 10
propagator:
  tau_init: 0.001
  stochastic: yes
  nw_target: 2000
  nadd: 3.0
  ncycle: 200000
hamiltonian:
  fermion:
    fcidump:
      path: FCIDUMP.spin_blocks
      unrestrict_style: blocks
