---
shift:
  damp: 0.5
stats:
  period: 5
propagator:
  tau_init: 0.001
  stochastic: yes
  nw_target: 10000
  nadd: 0.0
  ncycle: 2000
hamiltonian:
  fermion:
    hubbard:
      site_shape: [3, 4]
      boundary_conds: [1, 1]
      repulsion: 4.0
reference:
  mbf_init:
    neel: yes
