---
shift:
  damp: 0.5
  nw_targets: [200]
stats:
  period: 5
wavefunction:
  nw_init: 100
  load_large_ci:
    path: 'M7.large.h5'
reference:
  assume_hf_like: yes
propagator:
  tau_init: 0.1
  stochastic: yes
  ncycle: 500000
hamiltonian:
  fermion:
    fcidump:
      path: FCIDUMP
mae:
  filling_algorithm: outer_product
  rdm:
    save: yes
    ranks: [1, 2, 3]
    spinfree: yes
  delay: 1000
  ncycle: 100000
