---
shift:
  damp: 0.5
stats:
  period: 5
wavefunction:
  nw_init: 100
reference:
  assume_hf_like: yes
propagator:
  tau_init: 0.1
  stochastic: no
  nw_target: 200
  ncycle: 500000
  semistochastic:
    size: 28
    period: 20
    period: 1000
hamiltonian:
  fermion:
    fcidump:
      path: FCIDUMP
mae:
  rdm:
    save: yes
    ranks: [1, 2, 3]
    spinfree: yes
  delay: 1000
  ncycle: 100

