---
shift:
  damp: 0.1
stats:
  period: 5
wavefunction:
  nw_init: 100
propagator:
  tau_init: 0.001
  stochastic: yes
  nw_target: 5000
  nadd: 3.0
  ncycle: 20000
hamiltonian:
  fermion:
    fcidump: yes
reference:
  redef_thresh: 2.0
  mbf_init:
    fermion: [[0, 1, 5, 6, 7, 11]]
