---
shift:
  damp: 0.5
stats:
  period: 5
wavefunction:
  nw_init: 100
reference:
  assume_hf_like: yes
propagator:
  tau_init: 0.001
  stochastic: yes
  nw_target: 2000
  nadd: 3.0
  ncycle: 500000
  semistochastic:
    size: 28
    delay: 100
hamiltonian:
  fermion:
    fcidump:
      path: FCIDUMP
mae:
  rdm:
    archive:
      save: yes
    ranks: [1, 2, 3]
    spinfree: yes
  delay: 10000
  ncycle: 100

