---
shift:
  damp: 0.5
  nw_targets: [200]
stats:
  period: 5
wavefunction:
  nw_init: 100
reference:
  assume_hf_like: yes
propagator:
  tau_init: 0.1
  stochastic: no
  ncycle: 500000
  semistochastic:
    size: 28
    delay: 10
hamiltonian:
  fermion:
    fcidump:
      path: FCIDUMP
mae:
  on_the_fly: no
  rdm:
    save: yes
    ranks: [1, 2, 3]
    fock_4rdm:
      fock_path: fock_diag.h5
    spinfree: yes
  delay: 2000
  ncycle: 10

