---
shift:
  damp: 0.5
stats:
  period: 5
propagator:
  tau_init: 0.001
  stochastic: yes
  nw_target: 10000
  nadd: 0.0
  ncycle: 20000
hamiltonian:
  boson:
    hubbard:
      site_shape: [4]
      boundary_conds: [1]
      repulsion: 1.7
reference:
  mbf_init:
    boson: [[1, 1, 1, 1]]
