---
shift:
  damp: 0.2
  nw_targets: [1000]
stats:
  period: 5
wavefunction:
  nw_init: 100
  load: yes
propagator:
  tau_init: 0.001
  stochastic: yes
  nadd: 3.0
  ncycle: 20000
hamiltonian:
  fermion:
    fcidump: yes
