---
shift:
  damp: 0.5
stats:
  period: 5
wavefunction:
  nw_init: 10
  ci_pmntr:
    delta_k: 0.7
    max_exlvl: 4
    cancellation: yes
propagator:
  tau_init: 0.001
  stochastic: yes
  nw_target: 3000
  nadd: 3.0
  ncycle: 40000
hamiltonian:
  fermion:
    fcidump: yes
