---
shift:
  damp: 0.1
  nw_targets: [4000]
stats:
  period: 5
wavefunction:
  nw_init: 10
propagator:
  tau_init: 0.01
  stochastic: yes
  nadd: 3.0
  ncycle: 40000
hamiltonian:
  fermion:
    fcidump:
      path: FCIDUMP.spin_blocks
      unrestrict_style: blocks
