name: CMake

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
env:
  BUILD_TYPE: Release
  HOME_DIR: /home/user
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/robert-anderson/m7_tester
      options: --user user
      credentials:
        username: robert-anderson
        password: ${{ secrets.DOCKER_REGISTRY_PAT }}

    steps:
    - name: Report Runner Resources
      run: lscpu && free -h

    - name: Checkout
      run: ${{env.HOME_DIR}}/checkout.sh

    - name: Configure CMake (Fermion, real)
      run: ${{env.HOME_DIR}}/cmake.sh Release fermion no

    - name: Build (Fermion, real)
      run: ${{env.HOME_DIR}}/build.sh Release fermion no 2

    - name: Serial unit test (Fermion, real)
      run: ${{env.HOME_DIR}}/unittest.sh Release fermion no 1

    - name: Parallel unit test (Fermion, real)
      run: ${{env.HOME_DIR}}/unittest.sh Release fermion no 2