name: CMake

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  ROOT_DIR: /home/tester
  SRC_DIR: /home/tester/M7
  BUILD_DIR: /home/tester/build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/robert-anderson/m7_tester
      options: --user tester
      credentials:
        username: robert-anderson
        password: ${{ secrets.DOCKER_REGISTRY_PAT }}

    steps:
    - uses: actions/checkout@v3

    - name: Report Runner Resources
      run: lscpu && free -h

    - name: Checkout
      working-directory: ${{env.ROOT_DIR}}
      run: git clone https://github.com/robert-anderson/M7.git && mkdir ${{env.BUILD_DIR}}

    - name: Configure CMake
      working-directory: ${{env.BUILD_DIR}}
      run: cmake ${{env.SRC_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{env.BUILD_DIR}}
      run: make -j 2

    - name: SerialUnitTest
      working-directory: ${{env.BUILD_DIR}}
      run: test/unittest --gtest_filter=*

    - name: ParallelUnitTest
      working-directory: ${{env.BUILD_DIR}}
      run: mpirun -n 2 test/unittest --gtest_filter=*