name: CMake

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/robert-anderson/m7_tester
      options: --user user
      credentials:
        username: robert-anderson
        password: ${{ secrets.DOCKER_REGISTRY_PAT }}

    steps:
    - name: Report Runner Resources
      run: lscpu && free -h

    - name: Checkout
      working-directory: ${{env.HOME_DIR}}
      run: checkout.sh

    # Fermion, real walkers
    - name: Configure CMake
      run: cmake.sh Release fermion no

    - name: Build
      run: build.sh Release fermion no 2

    - name: Serial unit test
      run: unittest.sh Release fermion no 1

    - name: Parallel unit test
      run: unittest.sh Release fermion no 2